---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mavenwebappdeployment
spec:
 replicas: 1
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: mavenwebapp
 template:
  metadata:
   name: mavenwebapppod
   labels:
     app: mavenwebapp	 
  spec: 
    containers:
    - name: mavenwebappcontainer
      image: rasukuntanagesh/brinkerrestaurant
      imagePullPolicy: Always
      ports:
      - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
 name: mavenwebappsvc
spec:
  type: NodePort
  selector:
   app: mavenwebapp
  ports:
   - port: 80
     targetPort: 9091
     nodePort: 30785
...
